name: CI/CD Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to EC2 over SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd ~/CREDIT-FRAUD-INGESTION-API || git clone https://github.com/anupari14/CREDIT-FRAUD-INGESTION-API.git && cd CREDIT-FRAUD-INGESTION-API
          git pull origin main
          docker build -t CREDIT-FRAUD-INGESTION-API .
          docker stop api || true
          docker rm api || true
          docker run -d --name api -p 8000:8000 --env-file .env CREDIT-FRAUD-INGESTION-API
